steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'alpine-extra', '-t', 'gcr.io/anza-maliza/anza-pandoc-extra', '-f', 'alpine/Dockerfile', 'alpine']
images:
- 'gcr.io/anza-maliza/anza-pandoc-extra'
